### ISSUE TITLE
Definir historia de usuario

### ISSUE THREAD

**Issue by Lu-Pereira** [crismantovani/SAP005-social-network#3]
Definir historia de usuario

**Comment by Elis-ctrl** [comment]
Segue form para desmistificação de persona

https://docs.google.com/forms/d/1xtu0Lfw1LY_Zkqj2iOOS_DL7CmEwDflpmVFyOgRJHEk/edit

**Comment by Elis-ctrl** [comment]
Qual problema o produto resolve/para que ele serve para esses
usuarios?

Esta rede social é voltada para saude e esportes, ela 
transporta os tópicos bem mais fundamentados, auxiliando 
os usuarios a terem as informações claras e precisas.

**Comment by crismantovani** [comment]
## Histórias de Usuário 📄

### História de usuário 1
Como usuário **novo**, poder:

- [ ] Poder criar uma conta com e-mail e senha válidos para iniciar a sessão na Rede Social.
- [ ] Ter a opção "_Conectar com minha conta Google_".

### História de Usuário 2

- [ ] Como usuário **logado**, poder:
- [ ] Criar, editar, e apagar posts no mesmo lugar.
- [ ] Ver todos os posts que criei até o momento.
- [ ] Escrever, salvar, editar ou apagar um comentário em minhas publicações.
- [ ] Dar like e ver a contagem de likes em minhas publicações
- [ ] Visualizar meu perfil criado, editá-lo e alterar minha foto de perfil.
- [ ] Adicionar fotos aos meus posts.

**Comment by crismantovani** [comment]
## Histórias de Usuário 📄

### História de usuário 1
Como usuário **novo**, poder:

- [ ] Poder criar uma conta com e-mail e senha válidos para iniciar a sessão na Rede Social.
- [ ] Ter a opção "_Conectar com minha conta Google_".

### História de Usuário 2

- [ ] Como usuário **logado**, poder:
- [ ] Criar, editar, e apagar posts no mesmo lugar.
- [ ] Ver todos os posts que criei até o momento.
- [ ] Escrever, salvar, editar ou apagar um comentário em minhas publicações.
- [ ] Dar like e ver a contagem de likes em minhas publicações
- [ ] Visualizar meu perfil criado, editá-lo e alterar minha foto de perfil.
- [ ] Adicionar fotos aos meus posts.
